filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/*.log
  fields:
    app: elk

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
